### PR TITLE
fix enumerateDevices + refactoring + improvements

### PR DESCRIPTION
**Pull request by miroslavpejic85**
`fix enumerateDevices` - Ref: https://github.com/Dirvann/mediasoup-sfu-webrtc-video-rooms/issues/12
`refactoring + improve UI` using [bootstrap](https://getbootstrap.com) & [fontawesome](https://fontawesome.com):

`Join`

join

`Room`

room

`Video border`

room-video

<br>

Logs output:

log-refactoring

<br>

Update dependencies - `0 vulnerabilities`

update-dependencies

<br>

Add [prettier](https://prettier.io) as default code formatter

prettier-code-formatter

```js
    "devDependencies": {
        "prettier": "2.3.2"
    }
```

<br>

Update README

pull-requests

### CODE REVIEW

**Comment by Dirvann** [comment]
Thanks for the contribution! 
Just some suggestions
how about the prettier with this configuration:
```
module.exports= {
  semi: false,                              // supported with node and lighter on the eyes
  trailingComma: 'none',
  printWidth: 120,
  tabWidth: 2
}
```

Also the package-lock.json shouldn't be removed as it contains the exact versions of the packages to be installed.

**Comment by Dirvann** [comment]
I will also not be very active this half of August as I have other things I'm currently busy with

**Comment by miroslavpejic85** [comment]
> Thanks for the contribution!
> Just some suggestions
> how about the prettier with this configuration:
> 
> ```
> module.exports= {
>   semi: false,                              // supported with node and lighter on the eyes
>   trailingComma: 'none',
>   printWidth: 120,
>   tabWidth: 2
> }
> ```
> 
> Also the package-lock.json shouldn't be removed as it contains the exact versions of the packages to be installed.

Hi @Dirvann, My pleasure!
If you prefer that config, that’s fine, ;) It was just a personal choice :slightly_smiling_face:
Regarding `package-lock.json` sorry, so I need to delete it from `.gitignore` and keep this current that I have now, right?
Keep in touch.

**Comment by Dirvann** [comment]
Thanks for the response. 
Yeah you can just put your package-lock.json if the application still works with it. And regarding the mediasoupclient.min.js I compiled it myself using browserify.

**Comment by miroslavpejic85** [comment]
But what I see, the package-lock.json is generated differently depending on whether they are on the mac or Linux OS ...
As I can see yours is like on my Linux OS :) For this reason I put it on `.gitignore` So that when one runs `npm install` it will create their own package-lock.json file depending on the OS, or I'm doing something wrong? :) Anyway, in Both MAC-LINUX works well. Regarding `browserify` If it doesn't take you a lot of time, can you explain to me how to build for example the latest?
Thanks to you, my pleasure to meet you.

**Review by Dirvann — APPROVED** [review]

**Pull request merged**
